#!/bin/sh -e

# instalar en /usr/local/bin/get-ip-address
# muestra la ip como "IP: 0.0.0.0"

/sbin/ip address | grep "inet " | grep -v "127.0.0." | awk '{ print $2 }' | awk -F/ '{ print " IP: " $1 }'